CREATE DATABASE ECOVISA;

USE ECOVISA;

CREATE TABLE TBLDEPARTAMENTO(
	ID	INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	ESTADO BIT NOT NULL
);

CREATE TABLE TBLCARGO(
	ID	INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	ESTADO BIT NOT NULL
);

CREATE TABLE TBLEMPLEADO(
	ID INT NOT NULL PRIMARY KEY,
	PRIMER_NOMBRE VARCHAR(50) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(50) NOT NULL,
	PRIMER_APELLIDO VARCHAR(50) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(50) NOT NULL,
	CEDULA  VARCHAR(15) NOT NULL UNIQUE,
	DOMICILIO VARCHAR(300), 
	TELEFONO INT,
	CORREO_ELECTRONICO VARCHAR(100), 
	ESTADO BIT NOT NULL CONSTRAINT CK_ESTADO_EMPLEADO CHECK (ESTADO IN (0, 1)),
	IDDEPARTAMENTO_LABORAL INT NOT NULL,
	IDCARGO INT NOT NULL,
	CONSTRAINT FKEMPLEADO_DEPTO FOREIGN KEY (IDDEPARTAMENTO_LABORAL) REFERENCES TBLDEPARTAMENTO(ID),
	CONSTRAINT FKEMPLEADO_CARGO FOREIGN KEY (IDCARGO) REFERENCES TBLCARGO(ID)
);


CREATE TABLE TBLGRUPO(
	ID	INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	ESTADO BIT NOT NULL	
);

CREATE TABLE TBLUSUARIO(
	ID	INTEGER NOT NULL PRIMARY KEY,
	NOMBREUSUARIO VARCHAR(200) NOT NULL,
	USUARIO	VARCHAR(30) NOT NULL,
	CONTRASENA VARCHAR(100) NOT NULL, 
	CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
	ESTADO BIT NOT NULL	CONSTRAINT CK_ESTADO_USUAIRO CHECK (ESTADO IN (0, 1)),
	IDEMPLEADO INTEGER NOT NULL,
	IDGRUPO INTEGER NOT NULL,
	CONSTRAINT FKUSUARIO_EMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES TBLEMPLEADO(ID),
	CONSTRAINT FKUSUARIO_GRUPO FOREIGN KEY (IDGRUPO) REFERENCES TBLGRUPO(ID),
);

CREATE TABLE TBLMENU(
	ID INT NOT NULL,
	NOMBREMENU VARCHAR(200) NOT NULL,
	UBICACION VARCHAR(500),
	POSICION INT NOT NULL,
	IDPADRE INT NOT NULL,
	CONSTRAINT PK_MENU PRIMARY KEY (ID),
	CONSTRAINT FK_MENU_MENU FOREIGN KEY (IDPADRE) REFERENCES TBLMENU(ID)
);
