CREATE PROCEDURE [dbo].[PCDINSERTAR_EMPLEADO] (@strPrimerNombre VARCHAR(50), @strSegundoNombre VARCHAR(50), @strPrimerApellido VARCHAR(50), @strSegundoApellido VARCHAR(50), @strCedula VARCHAR(15), @strDomicilio VARCHAR(300), @intTelefono INT, @strCorreo VARCHAR(100), @intIdDepartamento INT, @intIdCargo INT)
AS
BEGIN 
	DECLARE @intId INT;
	BEGIN TRY
		BEGIN TRANSACTION 
			SELECT @intId  = COUNT(ID) FROM TBLEMPLEADO WHERE TRIM(UPPER(CEDULA)) = TRIM(UPPER(@strCedula));
			IF @intId > 0 
			BEGIN
				RAISERROR('Se encontró otro trabajador asociado a la cédula ingresada.', 11, 1);
			END
			INSERT INTO TBLEMPLEADO(ID, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CEDULA, DOMICILIO, TELEFONO, CORREO_ELECTRONICO, ESTADO, IDDEPARTAMENTO_LABORAL,IDCARGO)
			VALUES ((SELECT CASE WHEN MAX(ID) IS NULL THEN 1 ELSE MAX(ID) + 1 END FROM TBLEMPLEADO), @strPrimerNombre, @strSegundoNombre, @strPrimerApellido, @strSegundoApellido, @strCedula, @strDomicilio, @intTelefono, @strCorreo, 1, @intIdDepartamento, @intIdCargo);
			COMMIT TRANSACTION;
	 END TRY
	 BEGIN CATCH
		 /*INSERT INTO dbo.DB_Errors
			VALUES
		  (SUSER_SNAME(),
		   ERROR_NUMBER(),
		   ERROR_STATE(),
		   ERROR_SEVERITY(),
		   ERROR_LINE(),
		   ERROR_PROCEDURE(),
		   ERROR_MESSAGE(),
		   GETDATE());*/		
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END 
		DECLARE @Message varchar(MAX) = ERROR_MESSAGE(),
			@Severity int = ERROR_SEVERITY(),
			@State smallint = ERROR_STATE();
		RAISERROR (@Message, @Severity, @State);
		--RAISERROR(ERROR_MESSAGE(), ERROR_SEVERITY(), ERROR_STATE());

	 END CATCH
END;
GO

CREATE PROCEDURE [dbo].[PCDINSERTAR_USUARIO](@strNombreUsuario VARCHAR(200), @strUsuario VARCHAR(30), @strContrasena VARCHAR(100), @strCorreoElectronico VARCHAR(100), @boolEstado BIT, @intIdEmpleado INT, @intIdGrupo INT)
AS
BEGIN 
	DECLARE @intId INT,
		@intIdInsert INT;
	BEGIN TRY
		SET @intIdInsert = 1;
		BEGIN TRANSACTION 
		SELECT @intId  = COUNT(ID) FROM TBLUSUARIO WHERE TRIM(UPPER(USUARIO)) = TRIM(UPPER(@strUsuario));
		IF @intId > 0 
		BEGIN
			RAISERROR('Se encontró otra cuenta de usuario con la misma credencial usuario.', 11, 1);
		END
		INSERT INTO TBLUSUARIO(ID, NOMBREUSUARIO, USUARIO, CONTRASENA, CORREO_ELECTRONICO, ESTADO, IDEMPLEADO, IDGRUPO)
		VALUES ((SELECT CASE WHEN MAX(ID) IS NULL THEN 1 ELSE @intIdInsert END FROM TBLUSUARIO), @strNombreUsuario, @strUsuario, @strContrasena, @strCorreoElectronico, @boolEstado, @intIdEmpleado, @intIdGrupo);
		COMMIT TRANSACTION;
	 END TRY
	 BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END 
		DECLARE @Message varchar(MAX) = ERROR_MESSAGE(),
			@Severity int = ERROR_SEVERITY(),
			@State smallint = ERROR_STATE();
		RAISERROR (@Message, @Severity, @State);
	 END CATCH
END;
GO

CREATE PROCEDURE [dbo].[PCDLISTARMENUS] AS
BEGIN
		WITH TBLAUX AS
		(		SELECT ID, NOMBREMENU, UBICACION, POSICION, 0 AS IDPADRE,
					(SELECT NOMBREMENU FROM TBLMENU PADRE WHERE PADRE.ID = MENU.IDPADRE) PADRE,
					0 AS NIVEL,
					0 AS HIJO
				FROM TBLMENU MENU WHERE ID = IDPADRE
			UNION ALL
				SELECT MENU.*, TBLPADRE.NIVEL + 1 AS NIVEL, CASE WHEN EXISTS(SELECT 1 FROM TBLMENU HIJO WHERE HIJO.IDPADRE = MENU.ID) THEN 1 ELSE 0 END AS HIJO FROM 
				(
					SELECT MENU.*, (SELECT NOMBREMENU FROM TBLMENU PADRE WHERE PADRE.ID = MENU.IDPADRE) PADRE
					FROM TBLMENU MENU WHERE ID <> IDPADRE AND UBICACION IS NOT NULL
				)MENU
				INNER JOIN TBLAUX TBLPADRE  ON MENU.IDPADRE = TBLPADRE.ID
		)SELECT * FROM TBLAUX ORDER BY POSICION;

END;
GO

CREATE PROCEDURE [dbo].[PCDVALIDAR_USUARIO](@strUsuario VARCHAR(30), @strContrasena VARCHAR(100))
AS
BEGIN
	SELECT * FROM TBLUSUARIO WHERE TRIM(UPPER(USUARIO)) = TRIM(UPPER(@strUsuario)) AND CONTRASENA = @strContrasena;
END;
GO