CREATE VIEW [dbo].[VWLISTAR_CARGOS]
AS
	SELECT ID, DESCRIPCION, ESTADO, CASE WHEN ESTADO = 1 THEN 'Activo' ELSE 'Inactivo' END STRESTADO FROM TBLCARGO;
GO

CREATE VIEW [dbo].[VWLISTAR_DEPARTAMENTOS]
AS
	SELECT ID, DESCRIPCION, ESTADO, CASE WHEN ESTADO = 1 THEN 'Activo' ELSE 'Inactivo' END STRESTADO  FROM TBLDEPARTAMENTO;
GO

CREATE VIEW [dbo].[VWLISTAR_EMPLEADO]
AS 
	SELECT EMPLEADO.ID, PRIMER_NOMBRE + ' ' + SEGUNDO_NOMBRE + ' ' + PRIMER_APELLIDO + ' ' + SEGUNDO_APELLIDO AS TRABAJADOR, CEDULA, TELEFONO, CORREO_ELECTRONICO, IDDEPARTAMENTO_LABORAL, DPTO.DESCRIPCION AS DEPARTAMENTO,
		IDCARGO,  CARGO.DESCRIPCION AS CARGO
	FROM TBLEMPLEADO EMPLEADO
	INNER JOIN TBLDEPARTAMENTO DPTO ON EMPLEADO.IDDEPARTAMENTO_LABORAL = DPTO.ID
	INNER JOIN TBLCARGO CARGO ON EMPLEADO.IDCARGO = CARGO.ID;
GO

